### PR TITLE
indexer: fix getCoinsByAddress AssertionError

### LINKED ISSUE #118: ERR_ASSERTION when requesting UTXOs for a specific address
When I try to get UTXOs (endpoint `/coin/address/${address}`) for the address `qqqqvm6vn3uvh6tcqk5kl0gt0ygzte5lay9yhumssf` the following error is thrown:

```
{
  "error": {
    "type": "AssertionError",
    "code": "ERR_ASSERTION",
    "message": "false == true"
  }
}
```

I installed cloning the GitHub repository, and I'm using the branch master, wich is currently updated with all commits.

For other addresses there is no error.

The following trace can be found in the log file:

```
[D:2018-12-07T19:55:46Z] (http) Request for method=GET path=/coin/address/qqqqvm6vn3uvh6tcqk5kl0gt0ygzte5lay9yhumssf (10.120.2.47).
[E:2018-12-07T19:55:46Z] (node) false == true
AssertionError [ERR_ASSERTION]: false == true
    at AddrIndexer.getCoinsByAddress (/home/ec2-user/bcash/lib/indexer/addrindexer.js:163:9)
    at <anonymous>
```

### PR DESCRIPTION
**Pull request by tuxcanfly**
fixes #118 

address indexer was incorrectly failing to remove coins from transaction inputs, if the transaction was ordered before it's parent. Just like chain, we need to handle this by iterating and adding all outputs first, then _iterating_ again to delete inputs. The reverse needs to handled when unindexing.

Added regression test which covers this case. Tested it fails before the fix, and the fix makes it pass.

Thanks for spotting @jeansouza

### CODE REVIEW

**Comment by jeansouza** [comment]
@tuxcanfly thank you man! :)

File: lib/indexer/addrindexer.js [hunk 1]
```diff
@@ -99,12 +102,26 @@ class AddrIndexer extends Indexer {
...
+
+        b.del(layout.C.encode(addr, hash, i));
+      }
+    }
+
+    for (let i = 0; i < block.txs.length; i++) {
+      const tx = block.txs[i];
       if (!tx.isCoinbase()) {
         for (const {prevout} of tx.inputs) {
           const {hash, index} = prevout;
```
Comment (nodar-chkuaselidze) [inline lib/indexer/addrindexer.js]: We need to make sure inputs are not part of the current block.

Comment (tuxcanfly) [reply lib/indexer/addrindexer.js]: Thanks, fixed.
